name: finbert
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - pip
  - numpy>=1.23
  - pandas>=1.5
  - nltk
  - tqdm
  - ipykernel
  - sentence-transformers>=2.2
  - faiss-cpu
  - pip:
      - torch==2.2.1
      - transformers==4.37.2
      - scikit-learn==1.3.2
      - textblob
      - spacy==3.5.4
